version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t .

  build:
    commands:
      - echo "Zipping source for Elastic Beanstalk..."
      - zip -r app.zip . -x '*.git*' '*.venv*' '*__pycache__*'

artifacts:
  files:
    - app.zip